# Site settings
title: Open Source Design
email:
description: > # this means to ignore newlines until "baseurl:"
  We are a community of designers and developers aiming to push more
  open design processes and improve the user experience and interface
  design of open source software.

#baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://opensourcedesign.net" # the base hostname & protocol for your site
exclude: ["bower_components", "node_modules", "grunt", "sass", "scripts", "bower.json", "package.json", "README.md"]

twitter_username: opensrcdesign
github_username:  opensourcedesign

#Not check data in vendor
exclude: [vendor]

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  organization:
    output: true
    permalink: /organization/:path/
  resources:
    output: true
    permalink: /resources/:path/
  people:
    output: true
    permalink: /people/:path/

sass:
    style: compressed

source_url: "https://github.com/opensourcedesign/opensourcedesign.github.io/blob/master/"
edit_url: "https://github.com/opensourcedesign/opensourcedesign.github.io/edit/master/"
