# Site settings
title: Open Source Design
email:
description: > # this means to ignore newlines until "baseurl:"
  We are a community of designers and developers aiming to push more
  open design processes and improve the user experience and interface
  design of open source software.

#baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://opensourcedesign.net" # the base hostname & protocol for your site

exclude: ["bower_components", "node_modules", "grunt", "sass", "scripts", "bower.json", "package.json", "README.md"]

twitter_username: opensrcdesign
github_username:  opensourcedesign

# Build settings
markdown: kramdown
highlighter: rouge

collections:
  organization:
    output: true
    permalink: /organization/:path/
  resources:
    output: true
    permalink: /resources/:path/

sass:
    style: compressed

# Prose Config - what is seen at https://edit.opensourcedesign.net
# Docs: https://github.com/prose/prose/wiki/Prose-Configuration
prose:
  rooturl: 
  ignore:
    - '_includes'
    - '_layouts'
    - '_sass'
    - '_css'
    - 'fonts'
    - 'images'
    - 'js'
    - 'scripts'
    - '.gitignore'
    - '.travis.yml'
    - '_config-dev.yml'
    - '_config.yml'
    - 'CNAME'
    - 'feed.xml'
    - 'Gemfile'
    - 'index.html'
    - 'LICENSE'
    - 'Rakefile'
  siteurl: "http://opensourcedesign.net"
  media: 'media' 

# Enable the redirect_from plugin
#gems:
#  - jekyll-redirect-from
